doc/index.rst, fastcan/__init__.py, fastcan/_ssc.py, tests/test_fastcan.py, tests/test_ssc.py
=> FEAT add ssc function

README.rst, fastcan/_cancorr_fast.pyx, fastcan/_fastcan.py, pixi.lock
Change all memoryview slicing to pointers according to https://github.com/scikit-learn/scikit-learn/issues/17299. However, I did not find any performance improvement after run `pixi run time-h`
=> MNT remove memoryview slicing

README.rst, doc/conf.py, meson.build, pixi.lock, pyproject.toml
Test the new workflow at scikit-learn-contrib
=> Release 0.2.7

fastcan/_cancorr_fast.pyx, fastcan/_fastcan.py, pixi.lock, tests/test_fastcan.py
FEAT: add indices_exclude params to prohibit select some features without effect original feature orders.
=> FEAT add indices_exclude params

examples/plot_narx.py, fastcan/narx.py, pixi.lock, tests/test_narx.py
Add doc for: https://github.com/scikit-learn-contrib/fastcan/issues/29
=> DOC add example for basic usage of NARX

fastcan/_fastcan.py, fastcan/_minibatch.py, meson.build, pixi.lock, pyproject.toml
=> MNT fix minibatch X_transformed_ changes per loop

.github/workflows/ci.yml, .github/workflows/test.yml, examples/plot_pruning.py, pixi.lock
=> BUG fix pruning doc

.github/workflows/ci.yml, .github/workflows/test.yml, examples/plot_pruning.py, pixi.lock
=> DOC add random test times to mitigate inconsistent results on different OS

.github/workflows/lint.yml, .github/workflows/test.yml, pixi.lock, pyproject.toml
=> CI add test for macos and windows

.github/workflows/ci.yml, examples/plot_narx_msa.py, fastcan/narx.py, tests/test_narx.py
Specify Nelder-Mead method when coef_init="one_step_ahead". The method is slower, but gives better accuracy and no warning message.
=> DOC fix warning message in plot_narx_msa

examples/plot_narx_multi.py, pixi.lock, pyproject.toml
=> DOC add multi-output narx example

pixi.lock, pyproject.toml
=> FEAT add time-narx to evaluate opt speed of narx fit

fastcan/_cancorr_fast.pyx, fastcan/_fastcan.py, fastcan/_narx_fast.pyx, fastcan/meson.build, fastcan/narx.py, pixi.lock, pyproject.toml, tests/test_narx_jac.py
=> ENH speed up grad computation via Cython

fastcan/narx.py, pixi.lock, tests/test_narx.py
1. Output intercept when no poly term is assign to that output. It should be mean value for that output.
2. Update the warning message. We allow no poly term for some outputs, but at least one poly term should be assigned to one output.
3. For Jacobian of NARX, it should skip to compute dynamic part when no y in terms.
=> MNT output proper constant when some outputs only have intercepts

fastcan/narx.py, pixi.lock, tests/test_narx.py
=> MNT add error that some rows of feat_ids only have -1

fastcan/narx.py, pixi.lock, tests/test_narx.py
=> TST add equivalence check for sample weights

.github/workflows/lint.yml, .github/workflows/test.yml, fastcan/narx.py, tests/test_narx.py, tests/test_narx_jac.py
=> FEAT add param fit_intercept for NARX

.github/workflows/ci.yml, .github/workflows/lint.yml, .github/workflows/test.yml, pixi.lock, pyproject.toml, tests/test_narx.py
=> TST test printed message

fastcan/narx.py, fastcan/utils.py, pixi.lock, tests/test_narx.py, tests/test_utils.py
=> FEAT add mask_missing_values in utils

.github/workflows/static.yml, doc/multioutput.rst, doc/narx.rst, doc/ols_and_omp.rst, doc/pruning.rst, examples/plot_fisher.py, examples/plot_intuitive.py, examples/plot_pruning.py, examples/plot_redundancy.py, examples/plot_speed.py, fastcan/_cancorr_fast.pyx, fastcan/_fastcan.py, fastcan/narx.py, pixi.lock, pyproject.toml
=> MNT add codespell

examples/plot_pruning.py, pixi.lock
=> DOC add pca plot for data pruning example

.github/workflows/ci.yml, .github/workflows/emscripten.yml, .github/workflows/publish-pypi.yml, .github/workflows/wheel.yml, meson.build, pixi.lock, pyproject.toml
=> FEAT add wasm wheel in cibw

README.rst
=> DOC add readme for wasm wheel

doc/narx.rst, examples/plot_narx.py, examples/plot_narx_msa.py, fastcan/narx.py, fastcan/utils.py, tests/test_utils.py
=> MNT padding nan in time shift

.github/workflows/test.yml, .github/workflows/wheel.yml, pixi.lock, pyproject.toml
=> Add arm64 for linux

examples/plot_narx_msa.py, tests/test_narx.py
=> TST add test to check max_delay nan can split two time series

.github/workflows/static.yml, .github/workflows/test.yml, .github/workflows/wheel.yml, README.rst, pixi.lock
=> MNT update lock

fastcan/narx.py, tests/test_narx.py
Make NARX accept zero feature X to include AR models in NARX
=> FEAT add auto-regressive model in NARX

.github/workflows/emscripten.yml, .github/workflows/static.yml, .github/workflows/test.yml, .github/workflows/wheel.yml, .readthedocs.yml, README.rst, doc/conf.py, doc/diagram.puml, doc/index.rst, pixi.lock, pyproject.toml, scripts/rtd_pre_install.sh, tests/test_narx.py
=> DOC add plantuml C4 diagram

.github/workflows/emscripten.yml, .github/workflows/static.yml, .github/workflows/test.yml, .github/workflows/wheel.yml, README.rst, doc/narx.rst, examples/plot_forecasting.py, examples/plot_narx_msa.py, fastcan/narx/_base.py, fastcan/narx/_utils.py, fastcan/narx/tests/test_narx.py, pixi.lock, pyproject.toml
* add an CO2 forecasting example to demonstrate how to use NARX to build an AR model
* make NARX accept None input
* fix some bugs about gradient computation, when using AR models and y_init or y contains nan
=> DOC add AR model example

.github/workflows/emscripten.yml, .github/workflows/wheel.yml, examples/plot_speed.py
=> DOC smooth speed plot

.github/workflows/test.yml, fastcan/narx/_base.py, fastcan/narx/_utils.py, fastcan/narx/tests/test_narx.py, pixi.lock, pyproject.toml
=> MNT print narx to markdown table

fastcan/narx/_base.py, fastcan/narx/_narx_fast.pyx, fastcan/narx/tests/test_narx.py, fastcan/narx/tests/test_narx_jac.py, pixi.lock, pyproject.toml
1. rewrite _update_dydx and _predict in Cython
2. add profile task for narx
=> MNT speedup narx grad

.github/workflows/wheel.yml, meson.build, pixi.lock, pyproject.toml
1. As scikit-learn v1.7.2 provides wheels for Python 3.14, we can add them as well
2. Update lock, especially update scikit-learn version to 1.7.2
=> MNT add cp314 in cibw and update lock

.gitignore, doc/conf.py, doc/environment.yml, examples/plot_forecasting.py, fastcan/narx/tests/test_narx.py, pixi.lock, pyproject.toml, rtd-environment.yml, tests/test_fastcan.py
=> DOC add pyodide-http to enable fetch_openml in jupyterlite
